import { Store, HardHat, Users, Wrench, GraduationCap, MessageSquare } from 'lucide-react';
export const wards = ['Aujara','Gangawa','Gauza','Gunka','Harɓo Sabuwa','Harɓo Tsohuwa','Idanduna','Jabarna','Jahun','Kale','Kanwa'] as const;
export const services = [
 {id:'business',title:'Business premises registration',short:'Register a business',category:'Business & trade',icon:Store,description:'Formalise your enterprise and apply for a council premises certificate.',fields:['Business name','CAC / BN number (optional)','Trade category','Premises address','Owner NIN']},
 {id:'contractor',title:'Contractor & vendor enrollment',short:'Become a council vendor',category:'Business & trade',icon:HardHat,description:'Register your company for public works and council procurement.',fields:['Company name','CAC RC number','Public works category','Past job references'],document:'Tax clearance certificate'},
 {id:'cooperative',title:'Cooperative societies registration',short:'Register a cooperative',category:'Community',icon:Users,description:'Connect farmer clusters, artisan groups and market associations.',fields:['Society name','Executive committee details','Member count','Bank name','Account number']},
 {id:'skills',title:'Youth & artisans skills inventory',short:'Join the skills register',category:'Education & youth',icon:Wrench,description:'Register your skills and tooling needs for enterprise opportunities.',fields:['Date of birth','Skill category','Tooling needs','Certification status']},
 {id:'bursary',title:'Student bursary & allowance',short:'Apply for a bursary',category:'Education & youth',icon:GraduationCap,description:'Submit your student details for indigene verification and bursary screening.',fields:['Matriculation number','Institution name','Course of study','Year of study','BVN','Bank name','Account number'],document:'LGA indigene certificate'},
 {id:'complaint',title:'Civic complaints & feedback',short:'Report a community concern',category:'Community',icon:MessageSquare,description:'Report infrastructure faults or share concerns with the council.',fields:['Complaint category','Description'],document:'Supporting photograph (optional)'},
] as const;
export type ServiceId = typeof services[number]['id'];
export const welcome = 'Peace be upon you all. On behalf of the Jahun Local Government Council, I welcome you to our official civic and digital administration portal. Our commitment under our continuous development agenda is centered on empowering our agrarian communities, expanding education and rural access, providing reliable healthcare, and modernizing governance. Through this platform, our citizens across all eleven wards can directly access statutory services, apply for student bursaries, formalize their enterprises, and contribute to the economic prosperity of Jahun. We serve with transparency, equity, and dedication to the people.';
export function pageHead(title:string,description:string) { return {meta:[{title:`${title} | Jahun Local Government Council`},{name:'description',content:description},{property:'og:title',content:`${title} | Jahun Local Government Council`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}; }
