import { createServerFn } from '@tanstack/react-start';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { applicationSchema } from './application-schema';
import { z } from 'zod';
export const submitApplication=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((data:unknown)=>applicationSchema.parse(data)).handler(async({data,context})=>{
 if(data.documentPath){if(!data.documentPath.startsWith(`${context.userId}/`))throw new Error('Document access denied');const parts=data.documentPath.split('/');const filename=parts[1];if(!filename||parts.length!==2)throw new Error('Invalid document path');const {data:files,error}=await context.supabase.storage.from('civic-documents').list(context.userId,{search:filename});const file=files?.find(f=>f.name===filename);if(error||!file)throw new Error('Uploaded document was not found');if(Number(file.metadata?.['size'])>5*1024*1024)throw new Error('File exceeds 5MB');const {data:blob,error:downloadError}=await context.supabase.storage.from('civic-documents').download(data.documentPath);if(downloadError||!blob)throw new Error('Document cannot be validated');const bytes=new Uint8Array(await blob.slice(0,12).arrayBuffer());const isPdf=String.fromCharCode(...bytes.slice(0,5))==='%PDF-';const isJpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const isPng=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const isWebp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(data.service==='complaint'?!isJpeg&&!isPng&&!isWebp:!isPdf)throw new Error('Invalid document content');}
 const {data:row,error}=await context.supabase.from('service_applications').insert({citizen_id:context.userId,service:data.service,full_name:data.fullName,phone:data.phone,ward:data.ward,details:data.details,document_path:data.documentPath ?? null}).select('id,status,created_at').single();if(error)throw new Error('Your application could not be submitted. Please retry.');return row;
});
export const getApplications=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const {data,error}=await context.supabase.from('service_applications').select('id,service,status,ward,created_at,document_path,full_name,details').eq('citizen_id',context.userId).order('created_at',{ascending:false});if(error)throw new Error('Unable to load applications');return data;});

export const getDocumentLink=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({id:z.string().uuid()}).parse(v)).handler(async({data,context})=>{const {data:row}=await context.supabase.from('service_applications').select('document_path').eq('id',data.id).eq('citizen_id',context.userId).single();if(!row?.document_path)throw new Error('Document unavailable');const {data:link,error}=await context.supabase.storage.from('civic-documents').createSignedUrl(row.document_path,60);if(error)throw new Error('Document unavailable');return link.signedUrl;});
