import { createFileRoute,Link } from '@tanstack/react-router';
import { PageIntro } from '@/components/portal-shell';
import { Button } from '@/components/ui/button';
import { pageHead } from '@/lib/portal-data';
import fields from '@/assets/jahun-fields.jpg';
import councilLogo from '@/assets/jahun-council-logo.png';
export const Route=createFileRoute('/about')({head:()=>pageHead('About Jahun','Discover Jahun in Jigawa State: agricultural communities, local markets and eleven administrative wards.'),component:About});
function About(){return <main id="main"><PageIntro eyebrow="OUR PEOPLE. OUR HOME." title="About Jahun" description="An agricultural heartland in Jigawa State, Nigeria — connected by community, enterprise and shared ambition."/><section className="site-width page-body"><img src={fields} width={1920} height={1024} loading="lazy" className="w-full h-72 object-cover rounded-md" alt="Illustrative northern Nigerian farmland"/><div className="content-prose mt-8"><h2>Agriculture, community and opportunity</h2><p>Jahun’s communities are rooted in farming, market trade and local enterprise. Our council’s development priorities include education, rural access, reliable healthcare and municipal services.</p><div className="my-8 p-6 rounded-lg border border-border bg-card flex flex-col sm:flex-row items-center gap-6"><img src={councilLogo} width={112} height={112} className="w-28 h-28 object-contain shrink-0" alt="Official Seal of Jahun Local Government Council"/><div><h3 className="text-lg font-bold text-foreground">Official Seal of Jahun Local Government</h3><p className="text-sm text-muted-foreground mt-2 leading-relaxed">The official emblem of Jahun Local Government Council, Jigawa State, Nigeria. It features the Nigerian Coat of Arms atop the Jigawa territorial outline and agricultural green motifs symbolizing our fertile soils, harvest resilience, and unified civic dedication across all 11 wards.</p></div></div><h2>Eleven wards, one council</h2><p>The council serves Aujara, Gangawa, Gauza, Gunka, Harɓo Sabuwa, Harɓo Tsohuwa, Idanduna, Jabarna, Jahun, Kale and Kanwa.</p><Button asChild className="mt-6"><Link to="/wards">Discover our wards</Link></Button></div></section></main>}

