import { createFileRoute } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { useState } from 'react';
import { CheckCircle2,Clock,FileText,Search } from 'lucide-react';
import { PageIntro } from '@/components/portal-shell';
import { Button } from '@/components/ui/button';
import { usePortalAuth } from '@/components/portal-auth';
import { pageHead,services } from '@/lib/portal-data';
import { getApplications,getDocumentLink } from '@/lib/services.functions';
export const Route=createFileRoute('/applications')({head:()=>pageHead('My applications','Securely track your Jahun civic applications and supporting documents.'),component:Applications});
function Applications(){const{user,openLogin}=usePortalAuth();const fetch=useServerFn(getApplications),document=useServerFn(getDocumentLink);const[search,setSearch]=useState(''),[error,setError]=useState('');const query=useQuery({queryKey:['applications',user?.id],queryFn:()=>fetch(),enabled:!!user});return <main id="main"><PageIntro eyebrow="YOUR DIGITAL CIVIC DESK" title="My applications" description="Follow your application’s progress and access your submission references."/><section className="site-width page-body">{!user?<div className="py-12 text-center"><p className="mb-5">Sign in to view your private applications.</p><Button onClick={openLogin}>Citizen sign in</Button></div>:<><label className="field-label max-w-lg mb-8">Find by reference<input className="field" placeholder="Paste your application reference" value={search} onChange={e=>setSearch(e.target.value)} maxLength={36}/></label>{query.isPending?<p>Loading applications…</p>:query.isError?<div><p role="alert">Unable to load your applications.</p><Button onClick={()=>query.refetch()}>Try again</Button></div>:query.data?.length===0?<p>No applications submitted yet.</p>:<div className="space-y-5">{query.data?.filter(row=>row.id.includes(search.trim())).map(row=><article className="border border-border rounded-md bg-card p-6" key={row.id}><div className="flex flex-wrap justify-between gap-4"><h2 className="text-lg font-semibold">{services.find(s=>s.id===row.service)?.title}</h2><span className="text-xs text-primary bg-secondary px-3 py-2 rounded">{row.status}</span></div><p className="text-xs text-muted-foreground mt-3 break-all">Reference: {row.id}</p><p className="text-xs text-muted-foreground mt-2">{row.ward} · {new Date(row.created_at).toLocaleDateString('en-GB')}</p>{row.service==='bursary'&&<ol className="flex flex-wrap gap-5 mt-6 text-xs">{['Application Submitted','Under Ward Verification','Approved for Disbursement'].map((s,i)=><li key={s} className={`flex gap-2 items-center ${i<=['Application Submitted','Under Ward Verification','Approved for Disbursement'].indexOf(row.status)?'text-primary':'text-muted-foreground'}`}><CheckCircle2 size={16}/>{s}</li>)}</ol>}{row.document_path&&<Button variant="link" className="px-0 mt-3" onClick={async()=>{try{const url=await document({data:{id:row.id}});window.open(url,'_blank','noopener,noreferrer');}catch{setError('Your document could not be opened. Please retry.');}}}><FileText/>View supporting document</Button>}</article>)}{query.data&&query.data.length>0&&!query.data.some(row=>row.id.includes(search.trim()))&&<p>No matching reference found in your applications.</p>}</div>}<p role="alert" className="text-destructive mt-4">{error}</p></>}</section></main>}
