import { createFileRoute,Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { useState } from 'react';
import { PageIntro } from '@/components/portal-shell';
import { Button } from '@/components/ui/button';
import { usePortalAuth } from '@/components/portal-auth';
import { pageHead,services } from '@/lib/portal-data';
import { getOfficerQueue,reviewApplication,issueCertificate } from '@/lib/officers.functions';
export const Route=createFileRoute('/officers')({head:()=>pageHead('Council officer desk','Authorised council application review and business certificate issuance.'),component:OfficerDesk});
function OfficerDesk(){const{user,openLogin}=usePortalAuth();const get=useServerFn(getOfficerQueue),review=useServerFn(reviewApplication),issue=useServerFn(issueCertificate);const q=useQuery({queryKey:['officer-queue',user?.id],queryFn:()=>get(),enabled:!!user,retry:false});const[message,setMessage]=useState(''),[certificate,setCertificate]=useState(''),[busy,setBusy]=useState(false);return <main id="main"><PageIntro eyebrow="AUTHORISED COUNCIL STAFF" title="Council officer desk" description="Review civic submissions and issue certificates for approved business premises and indigene verification."/><section className="site-width page-body">{!user?<Button onClick={openLogin}>Officer sign in</Button>:q.isPending?<p>Checking council access…</p>:q.isError?<p role="alert">Your account does not have council officer access.</p>:<><p role="status" className="mb-5">{message}</p>{certificate&&<Button asChild className="mb-6"><Link to="/verify/$certificateId" params={{certificateId:certificate}}>View issued certificate</Link></Button>}{!q.data?.length&&<p>No applications awaiting review.</p>}<div className="space-y-5">{q.data?.map(row=><article key={row.id} className="border border-border bg-card rounded-md p-6"><h2 className="text-lg font-semibold">{services.find(s=>s.id===row.service)?.title}</h2><p className="text-sm mt-2">{row.full_name} · {row.ward} · {row.status}</p><p className="text-xs text-muted-foreground mt-2 break-all">{row.id}</p><form className="flex gap-3 mt-5 flex-wrap" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const status=new FormData(e.currentTarget).get('status');await review({data:{id:row.id,status:status as 'APPROVED'}});await q.refetch();setMessage('Application status updated.');}catch(err){setMessage(err instanceof Error?err.message:'Review failed');}finally{setBusy(false);}}}><select aria-label={`Status for ${row.id}`} name="status" className="field max-w-xs">{(row.service==='bursary'?['Under Ward Verification','Approved for Disbursement','REJECTED']:row.service==='indigene'?['Under Ward Verification','APPROVED','REJECTED']:row.service==='complaint'?['INVESTIGATING','RESOLVED','REJECTED']:['APPROVED','REJECTED']).map(s=><option key={s}>{s}</option>)}</select><Button disabled={busy}>Save review</Button>{row.service==='business'&&row.status==='APPROVED'&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{try{const cert=await issue({data:{id:row.id}});setCertificate(cert.id);}catch(err){setMessage(err instanceof Error?err.message:'Issuance failed');}}}>Issue certificate</Button>}</form></article>)}</div></>}</section></main>}
