CREATE TYPE public.app_role AS ENUM ('CITIZEN','DESK_OFFICER','REVENUE_ADMIN','SUPER_ADMIN');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL DEFAULT 'CITIZEN', UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_roles ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE TABLE public.citizens (id uuid PRIMARY KEY, full_name text NOT NULL, phone text NOT NULL, email text, ward text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.citizens TO authenticated; GRANT ALL ON public.citizens TO service_role;
ALTER TABLE public.citizens ENABLE ROW LEVEL SECURITY;
CREATE POLICY citizen_read ON public.citizens FOR SELECT TO authenticated USING(id=auth.uid()); CREATE POLICY citizen_insert ON public.citizens FOR INSERT TO authenticated WITH CHECK(id=auth.uid()); CREATE POLICY citizen_update ON public.citizens FOR UPDATE TO authenticated USING(id=auth.uid()) WITH CHECK(id=auth.uid());
CREATE TABLE public.service_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), citizen_id uuid NOT NULL, service text NOT NULL, full_name text NOT NULL, phone text NOT NULL, ward text NOT NULL, details jsonb NOT NULL DEFAULT '{}', document_path text, status text NOT NULL DEFAULT 'Application Submitted' CHECK(status IN ('Application Submitted','Under Ward Verification','Approved for Disbursement','APPROVED','REJECTED','INVESTIGATING','RESOLVED')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.service_applications TO authenticated; GRANT ALL ON public.service_applications TO service_role;
ALTER TABLE public.service_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY application_read ON public.service_applications FOR SELECT TO authenticated USING(citizen_id=auth.uid() OR public.has_role(auth.uid(),'DESK_OFFICER') OR public.has_role(auth.uid(),'SUPER_ADMIN'));
CREATE POLICY application_insert ON public.service_applications FOR INSERT TO authenticated WITH CHECK(citizen_id=auth.uid() AND status='Application Submitted');
CREATE INDEX applications_citizen ON public.service_applications(citizen_id,created_at DESC);
CREATE TABLE public.certificates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), application_id uuid NOT NULL REFERENCES public.service_applications(id), business_name text NOT NULL, ward text NOT NULL, issued_at timestamptz NOT NULL DEFAULT now(), revoked boolean NOT NULL DEFAULT false);
GRANT SELECT ON public.certificates TO anon,authenticated; GRANT ALL ON public.certificates TO service_role;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
CREATE POLICY public_certificate ON public.certificates FOR SELECT TO anon,authenticated USING(NOT revoked);
CREATE TABLE public.wards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, councilor_name text, contact_phone text);
GRANT SELECT ON public.wards TO anon,authenticated; GRANT ALL ON public.wards TO service_role;
ALTER TABLE public.wards ENABLE ROW LEVEL SECURITY;
CREATE POLICY ward_read ON public.wards FOR SELECT TO anon,authenticated USING(true);