import { Link } from '@tanstack/react-router';
import { ShieldCheck,ArrowUpRight,ChevronDown,Menu,X,Phone,MapPin,Mail,LogOut } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { usePortalAuth } from './portal-auth';
import crest from '@/assets/nigeria-crest.asset.json';
const nav=[['/','Home'],['/about','About Jahun'],['/administration','Administration'],['/wards','Wards & Districts'],['/services','E-Services Hub'],['/news','News & Gazette'],['/contact','Contact Us']] as const;
export function PortalHeader(){const[menu,setMenu]=useState(false);const{user,openLogin,signOut}=usePortalAuth();return <><a href="#main" className="skip-link">Skip to main content</a><div className="utility"><div className="site-width flex items-center justify-between gap-3"><span className="flex items-center gap-2"><ShieldCheck size={14}/><span>Official Portal of Jahun Local Government Council</span></span><div className="flex items-center gap-5"><Link to="/contact" className="hidden sm:flex items-center gap-2"><Phone size={12}/>Emergency contacts</Link><span className="hidden sm:block utility-divider"/><select aria-label="Language" defaultValue="en" className="language-select"><option value="en">English</option><option value="ha" disabled>Hausa — coming soon</option></select>{user?<Button variant="ghost" size="sm" onClick={signOut}><LogOut/>Sign out</Button>:<Button variant="ghost" size="sm" onClick={openLogin}>Citizen sign in</Button>}</div></div></div><header className="portal-header"><div className="site-width nav-row"><Link to="/" className="brand"><img src={crest.url} width={58} height={52} alt="Nigerian coat of arms"/><span><strong>JAHUN <span className="font-normal">LGA</span></strong><small>JIGAWA STATE, NIGERIA</small></span></Link><nav aria-label="Main navigation" className="desktop-nav">{nav.map(([to,label])=><Link key={to} to={to} activeOptions={{exact:true}} activeProps={{className:'nav-active'}}>{label}</Link>)}</nav><Button asChild className="nav-cta"><Link to="/services">Access E-Services<ArrowUpRight size={16}/></Link></Button><Button variant="ghost" size="icon" aria-label={menu?'Close menu':'Open menu'} className="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([to,label])=><Link key={to} to={to} onClick={()=>setMenu(false)}>{label}</Link>)}</nav>}</header></>}
export function PortalFooter(){return <footer className="portal-footer"><div className="site-width footer-grid"><div><Link to="/" className="brand"><img src={crest.url} width={54} height={48} alt=""/><span><strong>JAHUN LGA</strong><small>JIGAWA STATE, NIGERIA</small></span></Link><p className="mt-5 text-sm leading-7 max-w-sm">Serving our communities with transparency, equity and dedication to the people.</p></div><div><h3>Explore the council</h3><Link to="/about">About Jahun</Link><Link to="/administration">Our administration</Link><Link to="/wards">Wards & districts</Link></div><div><h3>Citizen services</h3><Link to="/services">E-Services hub</Link><Link to="/applications">Track your applications</Link><Link to="/news">Public gazette</Link></div><div><h3>Contact the council</h3><p className="flex gap-2 text-sm"><MapPin size={17}/>Council Secretariat, Jahun Town,<br/>Jigawa State, Nigeria.</p><Link to="/contact" className="mt-3">Contact & emergency directory <ArrowUpRight size={13}/></Link></div></div><div className="site-width footer-bottom"><span>© 2026 Jahun Local Government Council.</span><div><Link to="/privacy">Privacy & civic data</Link><a href="https://jigawastate.gov.ng" target="_blank" rel="noreferrer">Jigawa State Government ↗</a></div></div></footer>}
export function PageIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-intro"><div className="site-width"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></section>}
